
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -Wno-unused-variable
upload_port = COM7
;upload_speed = 460800
monitor_port = COM7
monitor_speed = 115200
lib_deps = 
	links2004/WebSockets@^2.4.1
	U8g2
	FastLED
	bblanchon/ArduinoJson@^6.21.3
